### ISSUE TITLE
Requirements file for project.

### ISSUE THREAD

**Issue by geo7** [andersle/valg#1] opened 2020-11-22 13:05 UTC
Feel free to close, just thought that it'd be nice to have a requirements file for the project so it's a bit easier for others to reproduce.

**Comment by andersle** [comment] 2020-11-22 21:54
I have added a requirements.txt file for the project. Didn't expect that someone else would look into the code. It can still be some work to reproduce the figures since the project assumes that geojson files from [kartverket](https://kartkatalog.geonorge.no/) are downloaded and that these are structured/extracted into individual geojson files for the municipalities. I didn't want to upload these files here since I do not own them.

**Comment by andersle** [comment] 2020-11-22 21:55
Closed by PR #3

**Closed as completed by andersle** 2020-11-22 21:54 UTC
